name: xdm-snap
base: core22
version: '8.0.25'
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
apps:
  xdm-snap:
    command: opt/xdman/xdm-app --no-sandbox --disable-seccomp-filter-sandbox
    extensions: [gnome]
    environment:
      GTK_USE_PORTAL: '1'
       
    plugs:
      - mount-observe
 

parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm-experimental-binaries/releases/download/$SNAPCRAFT_PROJECT_VERSION-beta/xdman_gtk_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    plugin: dump
    override-pull: |
      craftctl default
      sed -e 's|Exec=env GTK_USE_PORTAL=1 /opt/xdman/xdm-app %U|Exec=/opt/xdman/xdm-app %U|' -i usr/share/applications/xdm-app.desktop
    stage-packages:
      - yt-dlp
